=== shopware/shopware/src/Core/Framework/App/FlowAction/Schema/flow-action-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="flow-actions">
        <xs:complexType>
            <xs:annotation>
                <xs:documentation xml:lang="en">
                    Register your actions for Flow Builder.
                </xs:documentation>
            </xs:annotation>
            <xs:choice>
                <xs:element name="flow-action" type="flow-action" maxOccurs="unbounded" minOccurs="1"/>
            </xs:choice>
        </xs:complexType>
        <xs:unique name="uniqueActionName">
            <xs:selector xpath="flow-action"/>
            <xs:field xpath="name"/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="flow-action">
        <xs:all>
            <xs:element name="meta" type="meta"/>
            <xs:element name="headers" type="headers"/>
            <xs:element name="parameters" type="parameters"/>
            <xs:element name="config" type="config"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="headers">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="parameter" type="parameter"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="parameters">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="parameter" type="parameter"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="meta">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z][a-z.]*[a-z]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="translatableString" name="label" maxOccurs="unbounded"/>
            <xs:element type="translatableString" name="headline" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="translatableString" name="description" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="xs:anyURI" name="icon" minOccurs="0"/>
            <xs:element type="xs:string" name="badge" minOccurs="0"/>
            <xs:element type="xs:string" name="sw-icon" minOccurs="0"/>
            <xs:element type="xs:string" name="url"/>
            <xs:element type="xs:string" name="requirements"/>
            <xs:element type="xs:boolean" name="delayable"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="parameter">
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
    </xs:complexType>
    <xs:complexType name="config">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="input-field" type="input-field" maxOccurs="unbounded"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="option-collection">
        <xs:sequence>
            <xs:element name="option" type="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="label" type="translatableString" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="value" use="required"/>
    </xs:complexType>
    <xs:complexType name="translatableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="languageCode" default="en-GB"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="languageCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2,3}-[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="input-field">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="name" type="name"/>
            <xs:element name="label" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="place-holder" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="helpText" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
            <xs:element name="options" type="option-collection" minOccurs="0"/>
            <xs:element name="required" type="xs:boolean" minOccurs="0" default="false"/>
        </xs:choice>
        <xs:attribute name="type" type="type" default="text"/>
    </xs:complexType>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z][a-zA-Z0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="textarea"/>
            <xs:enumeration value="text-editor"/>
            <xs:enumeration value="url"/>
            <xs:enumeration value="password"/>
            <xs:enumeration value="int"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="bool"/>
            <xs:enumeration value="checkbox"/>
            <xs:enumeration value="datetime"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="time"/>
            <xs:enumeration value="colorpicker"/>
            <xs:enumeration value="single-select"/>
            <xs:enumeration value="multi-select"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== shopware/shopware/tests/integration/php/Core/Framework/App/Manifest/_fixtures/test/Resources/flow-action.xml
<flow-actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gitlab.shopware.com/shopware/6/product/platform/-/raw/next-19083/update-app-manifest-xsd-for-flow-action/src/Core/Framework/App/FlowAction/Schema/flow-action-1.0.xsd">
    <flow-action>
        <meta>
            <name>telegram.send.message</name>
            <label>Telegram send message</label>
            <label lang="de-DE">Telegram send message DE</label>
            <label lang="nl-NL">Telegram send message NL</label>
            <headline>The headline App Flow Action</headline>
            <headline lang="de-DE">Die Ãœberschrift App Flow Action</headline>
            <description>Telegram send message description</description>
            <description lang="de-DE">Telegramm senden Nachrichtenbeschreibung</description>
            <url>https://test-flow.com</url>
            <sw-icon>default-communication-speech-bubbles</sw-icon>
            <requirements>orderAware</requirements>
            <requirements>customerAware</requirements>
        </meta>
        <headers>
            <parameter type="string" name="content-type" value="application/json"/>
        </headers>
        <parameters>
            <parameter type="string" name="message" value="string message"/>
        </parameters>
        <config>
            <input-field type="text">
                <name>text</name>
                <label>Text</label>
                <label lang="de-DE">Text DE</label>
                <place-holder>Enter Text...</place-holder>
                <place-holder lang="de-DE">Enter Text DE...</place-holder>
                <required>true</required>
                <defaultValue>Hello</defaultValue>
                <helpText>Help Text</helpText>
                <helpText lang="de-DE">Help DE</helpText>
            </input-field>
        </config>
    </flow-action>
</flow-actions>

=== shopware/shopware/src/Core/Framework/Test/App/Manifest/_fixtures/test/Resources/flow-action-v3.xml
<flow-actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gitlab.shopware.com/shopware/6/product/platform/-/raw/next-19083/update-app-manifest-xsd-for-flow-action/src/Core/Framework/App/FlowAction/Schema/flow-action-1.0.xsd">
    <flow-action>
        <meta>
            <name>slack.send.message</name>
            <label>Slack send message</label>
            <label lang="de-DE">Slack send message DE</label>
            <label lang="nl-NL">Slack send message NL</label>
            <headline>The Headline for action</headline>
            <headline lang="de-DE">Die Schlagzeile zum Handeln</headline>
            <description>Slack send message description</description>
            <description lang="de-DE">Beschreibung der Slack-Sendenachricht</description>
            <url>https://test-flow.com</url>
            <sw-icon>default-communication-speech-bubbles</sw-icon>
            <requirements>orderAware</requirements>
            <requirements>customerAware</requirements>
        </meta>
        <headers>
            <parameter type="string" name="content-type" value="application/json"/>
        </headers>
        <parameters>
            <parameter type="string" name="message" value="string message"/>
        </parameters>
        <config>
            <input-field type="text">
                <name>text</name>
                <label>Text</label>
                <label lang="de-DE">Text DE</label>
                <place-holder>Enter Text...</place-holder>
                <place-holder lang="de-DE">Enter Text DE...</place-holder>
                <required>true</required>
                <defaultValue>Hello</defaultValue>
                <helpText>Help Text</helpText>
                <helpText lang="de-DE">Help DE</helpText>
            </input-field>
        </config>
    </flow-action>
</flow-actions>

=== shopware/shopware/src/Core/Framework/Test/App/FlowAction/_fixtures/valid/flowActionWithFlowActions.xml
<?xml version="1.0" encoding="utf-8" ?>
<flow-actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gitlab.shopware.com/shopware/6/product/platform/-/raw/next-19083/update-app-manifest-xsd-for-flow-action/src/Core/Framework/App/FlowAction/Schema/flow-action-1.0.xsd">
    <flow-action>
        <meta>
            <name>abc.cde.ccc</name>
            <badge>abc</badge>
            <label>First action app</label>
            <label lang="de-DE">First action app DE</label>
            <headline>Headline for action</headline>
            <headline lang="de-DE">Überschrift für Aktion</headline>
            <description>First action app description</description>
            <description lang="de-DE">First action app description DE</description>
            <url>https://example.xyz</url>
            <icon>resource/pencil</icon>
            <sw-icon>sw-pencil</sw-icon>
            <requirements>order</requirements>
            <requirements>customer</requirements>
        </meta>
        <headers>
            <parameter type="string" name="content-type" value="application/json"/>
            <parameter type="string" name="auth-token" value="token string"/>
        </headers>
        <parameters>
            <parameter type="string" name="to" value="{{ customer.name }}"/>
            <parameter type="string" name="from" value="{{ admin.name }}"/>
            <parameter type="string" name="message" value="string message"/>
        </parameters>
        <config>
            <input-field>
                <name>textField</name>
                <label>To</label>
                <label lang="de-DE">To DE</label>
                <place-holder>Enter to...</place-holder>
                <place-holder lang="de-DE">Enter to DE...</place-holder>
                <helpText>Help text</helpText>
                <helpText lang="de-DE">Help text DE</helpText>
                <required>true</required>
                <defaultValue>Shopware 6</defaultValue>
            </input-field>
            <input-field>
                <name>textField</name>
                <label>From</label>
                <label lang="de-DE">From</label>
                <place-holder>Enter from...</place-holder>
                <place-holder lang="de-DE">Enter from...</place-holder>
                <required>true</required>
                <defaultValue>Shopware 6</defaultValue>
            </input-field>
            <input-field type="text">
                <name>textField</name>
                <label>Message</label>
                <label lang="de-DE">Message</label>
                <place-holder>Enter message...</place-holder>
                <place-holder lang="de-DE">Enter message...</place-holder>
                <required>true</required>
                <defaultValue>Hello</defaultValue>
            </input-field>
            <input-field type="single-select">
                <name>mailMethod</name>
                <options>
                    <option value="smtp">
                        <label>English label</label>
                        <label lang="de-DE">German label</label>
                    </option>
                    <option value="pop3">
                        <label>English label</label>
                        <label lang="de-DE">German label</label>
                    </option>
                </options>
            </input-field>
        </config>
    </flow-action>
</flow-actions>

=== shopware/shopware/tests/integration/php/Core/Framework/App/Manifest/_fixtures/test/Resources/flow-action-v2.xml
<flow-actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://gitlab.shopware.com/shopware/6/product/platform/-/raw/next-19083/update-app-manifest-xsd-for-flow-action/src/Core/Framework/App/FlowAction/Schema/flow-action-1.0.xsd">
    <flow-action>
        <meta>
            <name>telegram.send.message</name>
            <label>Telegram send message</label>
            <label lang="de-DE">Telegram send message DE</label>
            <label lang="nl-NL">Telegram send message NL</label>
            <description>Telegram send message description</description>
            <description lang="de-DE">Telegram send message description DE</description>
            <url>https://test-flow.com</url>
            <sw-icon>default-communication-speech-bubbles</sw-icon>
            <requirements>orderAware</requirements>
            <requirements>customerAware</requirements>
            <delayable>true</delayable>
        </meta>
        <headers>
            <parameter type="string" name="content-type" value="application/json"/>
        </headers>
        <parameters>
            <parameter type="string" name="message" value="string message"/>
        </parameters>
        <config>
            <input-field type="text">
                <name>text</name>
                <label>Text</label>
                <label lang="de-DE">Text DE</label>
                <place-holder>Enter Text...</place-holder>
                <place-holder lang="de-DE">Enter Text DE...</place-holder>
                <required>true</required>
                <defaultValue>Hello</defaultValue>
                <helpText>Help Text</helpText>
                <helpText lang="de-DE">Help DE</helpText>
            </input-field>
        </config>
    </flow-action>
    <flow-action>
        <meta>
            <name>slack.send.message</name>
            <badge>Slack</badge>
            <label>Slack send message</label>
            <label lang="de-DE">Slack send message DE</label>
            <label lang="nl-NL">Slack send message NL</label>
            <description>Slack send message description</description>
            <description lang="de-DE">Slack send message description DE</description>
            <url>https://test-flow.com</url>
            <sw-icon>default-communication-speech-bubbles</sw-icon>
            <requirements>orderAware</requirements>
            <requirements>customerAware</requirements>
        </meta>
        <headers>
            <parameter type="string" name="content-type" value="application/json"/>
        </headers>
        <parameters>
            <parameter type="string" name="message" value="string message"/>
        </parameters>
        <config>
            <input-field type="text">
                <name>text</name>
                <label>Text</label>
                <label lang="de-DE">Text DE</label>
                <place-holder>Enter Text...</place-holder>
                <place-holder lang="de-DE">Enter Text DE...</place-holder>
                <required>true</required>
                <defaultValue>Hello</defaultValue>
                <helpText>Help Text</helpText>
                <helpText lang="de-DE">Help DE</helpText>
            </input-field>
        </config>
    </flow-action>
</flow-actions>
