=== shopware/shopware/src/Core/System/SystemConfig/Schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="card" type="card" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueInputFieldName">
            <xs:selector xpath="card/input-field/name"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="card">
        <xs:sequence>
            <xs:element name="title" type="translatableString" maxOccurs="unbounded"/>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="input-field" type="input-field" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="component" type="component" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="component">
        <xs:sequence>
            <xs:element name="name" type="name"/>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="input-field">
        <xs:sequence>
            <xs:element name="name" type="name"/>
            <xs:element name="disabled" type="xs:boolean" minOccurs="0"/>
            <xs:element name="copyable" type="xs:boolean" minOccurs="0"/>
            <xs:element name="required" type="xs:boolean" minOccurs="0"/>
            <xs:element name="label" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="placeholder" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="helpText" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
            <xs:element name="options" type="option-collection" minOccurs="0"/>
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="type" default="text"/>
    </xs:complexType>
    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="int"/>
            <xs:enumeration value="text"/>
            <xs:enumeration value="bool"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="datetime"/>
            <xs:enumeration value="password"/>
            <xs:enumeration value="single-select"/>
            <xs:enumeration value="multi-select"/>
            <xs:enumeration value="textarea"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="translatableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="languageCode" default="en-GB"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="languageCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2}-[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="option-collection">
        <xs:sequence>
            <xs:element name="option" type="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="name" type="translatableString" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{4,}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== shopware/shopware/src/Core/System/Resources/config/systemWideLoginRegistration.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">
    <card>
        <title>General (all sales channels)</title>
        <title lang="de-DE">Allgemein (alle Verkaufskanäle)</title>

        <input-field type="bool">
            <name>isCustomerBoundToSalesChannel</name>
            <label>Bind customers to Sales Channel</label>
            <label lang="de-DE">Kunden an Sales Channel binden</label>
            <helpText>If the setting is activated, customers can register separately for each Saleschannel. Existing customers are not affected by this setting.</helpText>
            <helpText lang="de-DE">Wenn die Einstellung aktiviert ist, können sich Kunden separat für jeden Saleschannel registrieren. Bestehende Kunden sind von dieser Einstellung nicht betroffen.</helpText>
            <flag>FEATURE_NEXT_10555</flag>
        </input-field>
    </card>
</config>

=== shopware/shopware/src/Core/System/Resources/config/basicInformation.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">
    <card>
        <title>Basic information</title>
        <title lang="de-DE">Stammdaten</title>

        <input-field>
            <name>shopName</name>
            <label>Shop name</label>
            <label lang="de-DE">Shopname</label>
            <placeholder>Enter a shop name...</placeholder>
            <placeholder lang="de-DE">Gib den Shopnamen ein ...</placeholder>
        </input-field>

        <input-field>
            <name>email</name>
            <label>Shop owner's email address</label>
            <label lang="de-DE">Shopbetreiber-E-Mail-Adresse</label>
            <placeholder>Enter email address...</placeholder>
            <placeholder lang="de-DE">E-Mail-Adresse eingeben ...</placeholder>
        </input-field>

        <input-field type="bool">
            <name>familyFriendly</name>
            <label>Family friendly shop</label>
            <label lang="de-DE">Familienfreundlicher Shop</label>
            <helpText>Sets meta tag "isFamilyFriendly" for search engines</helpText>
            <helpText lang="de-DE">Setzt den Metatag "isFamilyFriendly" für Suchmaschinen</helpText>
        </input-field>

    </card>

    <card>
        <title>Shop pages</title>
        <title lang="de-DE">Shopseiten</title>

        <component name="sw-cms-page-select">
            <name>tosPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Layout for GTC pages</label>
            <label lang="de-DE">Shopseiten-Layout für AGB-Seiten</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>revocationPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Layout for revocation notices</label>
            <label lang="de-DE">Shopseiten-Layout für Widerrufsbelehrungen</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>shippingPaymentInfoPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Layout for payment and shipping information</label>
            <label lang="de-DE">Shopseiten-Layout für Versand- und Zahlungsarten</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>privacyPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Layout for privacy pages</label>
            <label lang="de-DE">Shopseiten-Layout für Datenschutz-Seiten</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>imprintPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Layout for an imprint</label>
            <label lang="de-DE">Shopseiten-Layout für ein Impressum</label>
            <placeholder>Select layout</placeholder>
            <placeholder lang="de-DE">Layout auswählen</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>404Page</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Layout for 404 pages</label>
            <label lang="de-DE">Shopseiten-Layout für 404-Seiten</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>maintenancePage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Shop page layout for maintenance pages</label>
            <label lang="de-DE">Shopseiten-Layout für Wartungsseiten</label>
            <placeholder>Select layout</placeholder>
            <placeholder lang="de-DE">Layout auswählen</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>contactPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Shop page layout for contact pages</label>
            <label lang="de-DE">Shopseiten-Layout für Kontaktseiten</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

        <component name="sw-cms-page-select">
            <name>newsletterPage</name>
            <entity>cms_page</entity>
            <pageType>page</pageType>
            <label>Shop page layout for newsletter pages</label>
            <label lang="de-DE">Shopseiten-Layout für Newsletterseiten</label>
            <placeholder>Assign layout...</placeholder>
            <placeholder lang="de-DE">Layout zuweisen ...</placeholder>
        </component>

    </card>

    <card>
        <title>Security and Privacy</title>
        <title lang="de-DE">Sicherheit und Datenschutz</title>

        <component name="sw-settings-captcha-select">
            <name>activeCaptchas</name>
            <label>Active captchas</label>
            <label lang="de-DE">Aktive Captchas</label>
            <placeholder>None</placeholder>
            <placeholder lang="de-DE">Keine</placeholder>
        </component>

        <component name="sw-switch-field">
            <name>acceptAllCookies</name>
            <bordered>bordered</bordered>
            <label>Show "Accept all cookies" button</label>
            <label lang="de-DE">"Alle Cookies akzeptieren"-Button anzeigen</label>
            <helpText>Shows a button which allows users to accept all cookies in the storefront</helpText>
            <helpText lang="de-DE">Zeigt einen Button an, der es Nutzern erlaubt alle Cookies in der Storefront zu akzeptieren</helpText>
        </component>

        <component name="sw-switch-field">
            <name>firstNameFieldRequired</name>
            <bordered>bordered</bordered>
            <label>Require first name in contact form</label>
            <label lang="de-DE">Telefonnummer als Pflichtfeld in Kontaktformular behandeln</label>
            <helpText>Sets first name input as required in contact form</helpText>
            <helpText lang="de-DE">Setzt das Feld Vorname als Pflichtfeld im Kontaktformular</helpText>
        </component>

        <component name="sw-switch-field">
            <name>lastNameFieldRequired</name>
            <bordered>bordered</bordered>
            <label>Require last name in contact form</label>
            <label lang="de-DE">Nachname als Pflichtfeld in Kontaktformular behandeln</label>
            <helpText>Sets last name input as required in contact form</helpText>
            <helpText lang="de-DE">Setzt das Feld Nachname als Pflichtfeld im Kontaktformular</helpText>
        </component>

        <component name="sw-switch-field">
            <name>phoneNumberFieldRequired</name>
            <bordered>bordered</bordered>
            <label>Require phone number in contact form</label>
            <label lang="de-DE">Telefonummer als Pflichtfeld in Kontaktformular behandeln</label>
            <helpText>Sets phone number input as required in contact form</helpText>
            <helpText lang="de-DE">Setzt das Feld Telefonnummer als Pflichtfeld im Kontaktformular</helpText>
        </component>
    </card>

</config>

=== shopware/shopware/tests/integration/php/Storefront/Theme/fixtures/Apps/noThemeCustomCss/Resources/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">

    <card>

        <title>No Theme Custom CSS App</title>

        <input-field type="bool">
            <name>noThemeCustomCssEnabled</name>
            <label>noThemeCustomCss enabled</label>
            <label lang="de-DE">noThemeCustomCss aktivieren</label>
            <defaultValue>0</defaultValue>
        </input-field>

        <input-field>
            <name>noThemeCustomCssBackGroundcolor</name>
            <label>Backgroundcolor</label>
            <label lang="de-DE">Hintergrundfarbe</label>
            <copyable>true</copyable>
            <css>no-theme-custom-css-backgroundcolor</css>
        </input-field>

        <input-field>
            <name>noThemeCustomCssFontcolor</name>
            <label>Fontcolor</label>
            <label lang="de-DE">Textfarbe</label>
            <copyable>true</copyable>
            <css>no-theme-custom-css-fontcolor</css>
            <defaultValue>#eee</defaultValue>
        </input-field>

        <input-field>
            <name>noThemeCustomCssBordercolor</name>
            <label>Bordercolor</label>
            <label lang="de-DE">Rahmenfarbe</label>
            <copyable>true</copyable>
            <css>no-theme-custom-css-bordercolor</css>
        </input-field>
    </card>

</config>

=== shopware/shopware/src/Core/System/Resources/config/sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../SystemConfig/Schema/config.xsd">
    <card>
        <title>Sitemap</title>
        <title lang="de-DE">Sitemap</title>

        <input-field type="int">
            <name>sitemapRefreshTime</name>
            <label>Refresh interval</label>
            <label lang="de-DE">Aktualisierungsinterval</label>
            <placeholder>Enter refresh interval (seconds)...</placeholder>
            <placeholder lang="de-DE">Gib ein Aktualisierungsinterval an (Sekunden) ...</placeholder>
            <helpText>Enter interval in seconds. (Active only in live mode.)</helpText>
            <helpText lang="de-DE">Gib einen Zeitraum in Sekunden ein. (Aktiv nur im Live-Modus.)</helpText>
        </input-field>

        <input-field type="single-select">
            <name>sitemapRefreshStrategy</name>
            <options>
                <option>
                    <id>1</id>
                    <name>Manually</name>
                    <name lang="de-DE">Manuell</name>
                </option>
                <option>
                    <id>2</id>
                    <name>Scheduled</name>
                    <name lang="de-DE">Geplant</name>
                </option>
                <option>
                    <id>3</id>
                    <name>Live</name>
                    <name lang="de-DE">Live</name>
                </option>
            </options>
            <label>Refresh strategy</label>
            <label lang="de-DE">Aktualisierungsmethode</label>
            <helpText>
                Manually: refresh via console command: php bin/console sitemap:generate.

                Scheduled: refresh via scheduled tasks (every 24 hours).

                Live: Refresh in intervals defined above, if Administration is opened.
            </helpText>
            <helpText lang="de-DE">
                Manuell: Aktualisierung über Konsolenbefehl php bin/console sitemap:generate.

                Geplant: Aktualisierung über geplante Tasks (alle 24 Stunden).

                Live: Aktualisierung in regelmäßigen Intervallen (definiere oben)- wenn Admin geöffnet.
            </helpText>
        </input-field>

    </card>
</config>

=== shopware/shopware/src/Core/Framework/Test/App/Lifecycle/_fixtures/withInvalidConfig/Resources/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">

    <card>
        <title>Basic configuration</title>
        <title lang="de-DE">Grundeinstellungen</title>
        <name>TestCard</name>
        <input-field>
            <name>email</name>
            <copyable>true</copyable>
            <label>eMail</label>
            <label lang="de-DE">E-Mail</label>
            <defaultValue>no-reply@shopware.de</defaultValue>
        </input-field>
        <component name="test">
            <name>notAllowed</name>
        </component>
    </card>
</config>

=== shopware/shopware/src/Core/Framework/Test/Plugin/_fixture/plugins/SwagTest/src/Resources/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/shopware/trunk/src/Core/System/SystemConfig/Schema/config.xsd">

    <card>
        <title>Configuration</title>
        <title lang="de-DE">Konfiguration</title>
        <input-field type="int">
            <name>intField</name>
            <label>Test field with default value</label>
            <defaultValue>7</defaultValue>
        </input-field>
        <input-field type="text">
            <name>textFieldWithoutDefault</name>
            <label>Test field without default value</label>
        </input-field>
        <input-field type="text">
            <name>textField</name>
            <label>Test field with default value</label>
            <defaultValue>string</defaultValue>
        </input-field>
        <input-field type="text">
            <name>textFieldNull</name>
            <label>Test field with default value null</label>
            <defaultValue>null</defaultValue>
        </input-field>
        <input-field type="bool">
            <name>switchField</name>
            <label>Test field with default value</label>
            <defaultValue>false</defaultValue>
        </input-field>
        <input-field type="float">
            <name>floatField</name>
            <label>Test field with default value</label>
            <defaultValue>0.349831239840912348</defaultValue>
        </input-field>
        <input-field type="price">
            <name>priceField</name>
            <label>Test price field</label>
            <defaultValue>null</defaultValue>
        </input-field>
        <input-field type="text">
            <name>numericTextField</name>
            <label>Test text field with a numeric string default value</label>
            <defaultValue>"100"</defaultValue>
        </input-field>
        <input-field type="multi-select">
            <name>multiSelectField</name>
            <label>Test multi select field with default values</label>
            <options>
                <option>
                    <id>value1</id>
                    <name>The first value</name>
                </option>
                <option>
                    <id>value2</id>
                    <name>The second value</name>
                </option>
                <option>
                    <id>value3</id>
                    <name>The third value</name>
                </option>
            </options>
            <defaultValue>["value1", "value2"]</defaultValue>
        </input-field>
    </card>
</config>

=== shopware/shopware/src/Core/System/Resources/config/seo.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/trunk/src/Core/System/SystemConfig/Schema/config.xsd">
    <card>
        <title>Settings</title>
        <title lang="de-DE">Einstellungen</title>

        <input-field type="bool">
            <name>redirectToCanonicalUrl</name>
            <label>Instead of setting Canonical URLs directly redirect via HTTP 301 to the current URL</label>
            <label lang="de-DE">Statt Canonical URLs direkt per HTTP 301 auf die aktuellste URL leiten</label>
            <helpText>This option affects all entities whose name can change. If deactivated, the redirection is initiated by Canonical. Activated it redirects to the current URL directly via HTTP 301.</helpText>
            <helpText lang="de-DE">Diese Option betrifft alle Entitäten, deren Name sich ändern kann. Die Weiterleitung wird im deaktivierten Zustand per Canonical angestoßen, während im aktiven Zustand direkt bei HTTP 301 auf die aktuellste URL weitergeleitet wird.</helpText>
        </input-field>
    </card>
</config>

=== shopware/shopware/src/Core/System/Test/SystemConfig/_fixtures/SwagExampleTest/Resources/config/card.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">

    <card>
        <title>Basic configuration</title>
        <title lang="de-DE">Grundeinstellungen</title>
        <input-field>
            <name>email</name>
            <copyable>true</copyable>
            <label>eMail</label>
            <label lang="de-DE">E-Mail</label>
            <placeholder>Enter your eMail address</placeholder>
            <placeholder lang="de-DE">Bitte gib deine E-Mail Adresse ein</placeholder>
        </input-field>

        <input-field type="int">
            <name>withoutAnyConfig</name>
        </input-field>

        <input-field type="single-select">
            <name>mailMethod</name>
            <options>
                <option>
                    <id>smtp</id>
                    <name>SMTP</name>
                </option>
                <option>
                    <id>pop3</id>
                    <name>POP3</name>
                </option>
            </options>
            <label>Mailing protocol</label>
            <label lang="de-DE">E-Mail Versand Protokoll</label>
            <placeholder>Choose your preferred transfer method</placeholder>
            <placeholder lang="de-DE">Bitte w√§hle dein bevorzugtes Versand Protokoll</placeholder>

            <flag>FEATURE_NEXT_102</flag>
        </input-field>

        <flag>FEATURE_NEXT_101</flag>
    </card>
</config>
