=== shopware/shopware/src/Core/System/SystemConfig/Schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="card" type="card" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueInputFieldName">
            <xs:selector xpath="card/input-field/name"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="card">
        <xs:sequence>
            <xs:element name="title" type="translatableString" maxOccurs="unbounded"/>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="input-field" type="input-field" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="component" type="component" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="component">
        <xs:sequence>
            <xs:element name="name" type="name"/>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="input-field">
        <xs:sequence>
            <xs:element name="name" type="name"/>
            <xs:element name="disabled" type="xs:boolean" minOccurs="0"/>
            <xs:element name="copyable" type="xs:boolean" minOccurs="0"/>
            <xs:element name="required" type="xs:boolean" minOccurs="0"/>
            <xs:element name="label" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="placeholder" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="helpText" type="translatableString" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
            <xs:element name="options" type="option-collection" minOccurs="0"/>
            <xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="type" default="text"/>
    </xs:complexType>
    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="int"/>
            <xs:enumeration value="text"/>
            <xs:enumeration value="bool"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="datetime"/>
            <xs:enumeration value="password"/>
            <xs:enumeration value="single-select"/>
            <xs:enumeration value="multi-select"/>
            <xs:enumeration value="textarea"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="translatableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="languageCode" default="en-GB"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="languageCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{2}-[A-Z]{2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="option-collection">
        <xs:sequence>
            <xs:element name="option" type="option" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="option">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="name" type="translatableString" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{4,}"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== shopware/shopware/src/Core/System/SystemConfig/Resources/config/basic-information.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd">
    <card>
        <title>Basic Information</title>
        <title lang="de-DE">Stammdaten</title>

        <input-field>
            <name>email</name>
            <label>Shopowner email address</label>
            <label lang="de-DE">Shopbetreiber E-Mail Adresse</label>
            <placeholder>Enter email</placeholder>
            <placeholder lang="de-DE">Gebe eine E-Mail ein</placeholder>
        </input-field>

        <input-field type="textarea">
            <name>address</name>
            <label>Address</label>
            <label lang="de-DE">Adresse</label>
            <placeholder>Enter address</placeholder>
            <placeholder lang="de-DE">Adresse eingeben</placeholder>
        </input-field>

        <input-field type="textarea">
            <name>bankAccount</name>
            <label>Bank account </label>
            <label lang="de-DE">Bankverbindung</label>
            <placeholder>Enter bank account</placeholder>
            <placeholder lang="de-DE">Bankverbindung eingeben</placeholder>
        </input-field>

        <input-field type="bool">
            <name>familyFriendly</name>
            <label>Shop is family friendly</label>
            <label lang="de-DE">Shop ist Familienfreundlich</label>
            <helpText>Will set the meta tag "isFamilyFriendly" for search engines</helpText>
            <helpText lang="de-DE">Setzt den Metatag "isFamiliyFriendly" fÃ¼r Suchmaschinen</helpText>
        </input-field>
    </card>
</config>
