=== shopware/shopware/src/Core/System/CustomEntity/Xml/entity-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="entities">
        <xs:complexType>
            <xs:choice>
                <xs:element name="entity" type="entity" maxOccurs="unbounded" />
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="on-delete">
        <xs:restriction base="xs:string">
            <xs:enumeration value="set-null"/>
            <xs:enumeration value="cascade"/>
            <xs:enumeration value="restrict"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="entity">
        <xs:choice>
            <xs:element name="fields" maxOccurs="unbounded" type="field-list" minOccurs="1"/>
        </xs:choice>

        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="field-list">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="int" type="field-int-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="float" type="field-float-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="string" type="field-string-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="text" type="field-text-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="bool" type="field-bool-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="many-to-many" type="field-many-to-many-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="many-to-one" type="field-many-to-one-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="one-to-many" type="field-one-to-many-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="one-to-one" type="field-one-to-one-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="json" type="field-json-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="email" type="field-email-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="price" type="field-price-type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="date" type="field-date-type" maxOccurs="unbounded" minOccurs="0"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="field-int-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-float-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-string-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-text-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="allow-html" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-bool-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-json-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-email-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-price-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
    </xs:complexType>

    <xs:complexType name="field-date-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="translatable" default="false" />
    </xs:complexType>

    <xs:complexType name="field-many-to-many-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="reference" use="required" />
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="inherited" />
    </xs:complexType>

    <xs:complexType name="field-many-to-one-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="reference" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="inherited" />
        <xs:attribute type="on-delete" name="on-delete" use="required" />
    </xs:complexType>

    <xs:complexType name="field-one-to-many-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="reference" use="required" />
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="inherited" />
        <xs:attribute type="xs:boolean" name="reverse-required" default="false" />
        <xs:attribute type="on-delete" name="on-delete" use="required" />
    </xs:complexType>

    <xs:complexType name="field-one-to-one-type">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="reference" use="required" />
        <xs:attribute type="xs:boolean" name="required" default="false" />
        <xs:attribute type="xs:boolean" name="store-api-aware" use="required" />
        <xs:attribute type="xs:boolean" name="inherited" />
        <xs:attribute type="on-delete" name="on-delete" use="required" />
    </xs:complexType>
</xs:schema>

=== shopware/shopware/tests/unit/Core/System/CustomEntity/_fixtures/CustomEntityLifecycleServiceTest/withCustomEntities/plugin/src/Resources/entities.xml
<?xml version="1.0" encoding="utf-8" ?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../../../../src/Core/System/CustomEntity/Xml/entity-1.0.xsd">
    <entity name="ce_super_simple">
        <fields>
            <string name="test_string" store-api-aware="true"/>
        </fields>
    </entity>
    <!-- @todo NEXT-22697 - Re-implement, when re-enabling cms-aware -->
<!--    <entity name="ce_cms_aware" cms-aware="true">-->
    <entity name="ce_cms_aware">
        <fields>
            <json name="payload" store-api-aware="false" />
            <email name="email"  store-api-aware="false" />
            <price name="price" store-api-aware="false" />
            <date name="my_date" store-api-aware="false" />
        </fields>
    </entity>
    <entity name="ce_complex">
        <fields>
            <int name="position" store-api-aware="true" />
            <float name="rating" store-api-aware="true" />
            <string name="title" required="true" translatable="true" store-api-aware="true" />
            <text name="content" allow-html="true" translatable="true" store-api-aware="true" />
            <bool name="display" translatable="true" store-api-aware="true" />
            <json name="payload" store-api-aware="false" />
            <email name="email"  store-api-aware="false" />
            <price name="price" store-api-aware="false" />
            <date name="my_date" store-api-aware="false" />

            <many-to-many name="products" reference="product" store-api-aware="true" />
            <many-to-one name="top_seller_restrict" reference="product" store-api-aware="true" required="false" on-delete="restrict" />
            <many-to-one name="top_seller_cascade" reference="product" store-api-aware="true" required="true" on-delete="cascade" />
            <many-to-one name="top_seller_set_null" reference="product" store-api-aware="true" on-delete="set-null" />
            <one-to-one name="link_product_restrict" reference="product" store-api-aware="false" on-delete="restrict" />
            <one-to-one name="link_product_cascade" reference="product" store-api-aware="false" on-delete="cascade" />
            <one-to-one name="link_product_set_null" reference="product" store-api-aware="false" on-delete="set-null" />
            <one-to-many name="links_restrict" reference="category" store-api-aware="true" on-delete="restrict" />
            <one-to-many name="links_set_null" reference="category" store-api-aware="true" on-delete="set-null" />
            <one-to-many name="comments" reference="ce_blog_comment" store-api-aware="true" on-delete="cascade" reverse-required="true" />
            <many-to-many name="inherited_products" reference="product" store-api-aware="true" inherited="true"/>
            <many-to-one name="inherited_top_seller" reference="product" store-api-aware="true" required="false" inherited="true" on-delete="set-null"/>
            <one-to-one name="inherited_link_product" reference="product" store-api-aware="true" inherited="true" on-delete="set-null" />
        </fields>
    </entity>
</entities>

=== shopware/shopware/tests/integration/Core/System/CustomEntity/_fixtures/without-restrict-delete/Resources/entities.xml
<?xml version="1.0" encoding="utf-8" ?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/trunk/src/Core/Framework/App/Entities/Schema/entity-1.0.xsd">
    <entity name="custom_entity_blog">
        <fields>
            <int name="position" store-api-aware="true" />
            <float name="rating" store-api-aware="true" />
            <string name="title" required="true" translatable="true" store-api-aware="true" />
            <text name="content" allow-html="true" translatable="true" store-api-aware="true" />
            <bool name="display" translatable="true" store-api-aware="true" />
            <json name="payload" store-api-aware="false" />
            <email name="email"  store-api-aware="false" />

            <price name="price" store-api-aware="false" />
            <date name="my_date" store-api-aware="false" />
        </fields>
    </entity>

    <entity name="ce_blog_comment">
        <fields>
            <string name="title" required="true" translatable="true" store-api-aware="true" />
            <!-- <fk name="ce_blog_comments_id" required="true"   <<< defined over the one-to-many association -->
            <text name="content" allow-html="true" translatable="true" store-api-aware="true" />
            <email name="email"  store-api-aware="false" />
            <many-to-one name="recommendation" reference="product" store-api-aware="true" required="false" on-delete="set-null" />
        </fields>
    </entity>
</entities>

=== shopware/shopware/src/Core/Framework/Test/App/Entity/_fixtures/customEntities/Resources/entities.xml
<?xml version="1.0" encoding="utf-8" ?>
<entities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/trunk/src/Core/Framework/App/Entities/Schema/entity-1.0.xsd">
    <entity name="custom_entity_blog" store-api-aware="true">
        <fields>
            <int name="position" store-api-aware="true" />
            <float name="rating" store-api-aware="true" />
            <string name="title" required="true" translatable="true" store-api-aware="true" />
            <text name="content" allow-html="true" translatable="true" store-api-aware="true" />
            <bool name="display" translatable="true" store-api-aware="true" />
            <json name="payload" store-api-aware="false" />
            <email name="email"  store-api-aware="false" />
            <many-to-many name="products" reference="product" store-api-aware="true" />

            <one-to-many name="links" reference="category" store-api-aware="true" />
            <one-to-many name="comments" reference="custom_entity_blog_comment" store-api-aware="true" />
            <many-to-one name="top_seller" reference="product" store-api-aware="true" required="true" />
            <one-to-one name="link_product" reference="product" store-api-aware="false" />
        </fields>
    </entity>

    <entity name="custom_entity_blog_comment" store-api-aware="true">
        <fields>
            <string name="title" required="true" translatable="true" store-api-aware="true" />
            <text name="content" allow-html="true" translatable="true" store-api-aware="true" />
            <email name="email"  store-api-aware="false" />
            <many-to-one name="recommendation" reference="product" store-api-aware="true" required="false" />
        </fields>
    </entity>
</entities>
